services:
  motus:
    container_name: "${SERVER_NAME:-server}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    ports:
      - "10001:10001"
    networks:
      - webnet
      - redis
    env_file: .env
networks:
  webnet:
  redis:
    external: true
